name: Continuous Deployment

on:
  push:
    branches: ['master']
jobs:
  deploy_job:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: copy file via ssh password
      uses: appleboy/scp-action@master
      with:
        HOST: forkinthecode@nitron.se.rit.edu
        USERNAME: forkinthecode
        PORT: 22
        KEY: ${{ secrets.SSH_SECRET }}
        source: "."
        target: "/home/senior-projects/forkinthecode/public_html"
    - name: Executing remote command
      uses: appleboy/ssh-action@master
      with:
        HOST: forkinthecode@nitron.se.rit.edu
        USERNAME: forkinthecode
        KEY: ${{ secrets.SSH_SECRET }}
        PORT: 22
        script: |
          cd /home/senior-projects/forkinthecode
          chmod -R g+w public_html
